-- For the Metabase "Sample Database"
SELECT "PUBLIC"."ORDERS"."ID"         AS "ID",
       "PUBLIC"."ORDERS"."USER_ID"    AS "USER_ID",
       "PUBLIC"."ORDERS"."PRODUCT_ID" AS "PRODUCT_ID",
       "PUBLIC"."ORDERS"."SUBTOTAL"   AS "SUBTOTAL",
       "PUBLIC"."ORDERS"."TAX"        AS "TAX",
       "PUBLIC"."ORDERS"."TOTAL"      AS "TOTAL",
       "PUBLIC"."ORDERS"."DISCOUNT"   AS "DISCOUNT",
       "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT",
       "PUBLIC"."ORDERS"."QUANTITY"   AS "QUANTITY"
FROM "PUBLIC"."ORDERS" LIMIT 1048575